// Generated by 'unplugin-auto-import'
export {}
declare global {
  const IvueMessage: typeof import('ivue-material-plus/dist/unplugin-vue-components/es')['IvueMessage']
  const IvueNotice: typeof import('ivue-material-plus/dist/unplugin-vue-components/es')['IvueNotice']
}
