// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IvueAffix: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-affix')['default']
    IvueAutoComplete: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-auto-complete')['default']
    IvueAvatar: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-avatar')['default']
    IvueBadge: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-badge')['default']
    IvueBottomNav: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-bottom-nav')['default']
    IvueBottomNavItem: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-bottom-nav-item')['default']
    IvueBreadcrumbs: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-breadcrumbs')['default']
    IvueBreadcrumbsItem: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-breadcrumbs-item')['default']
    IvueButton: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-button')['default']
    IvueCarousel: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-carousel')['default']
    IvueCarouselItem: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-carousel-item')['default']
    IvueCascader: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-cascader')['default']
    IvueCheckbox: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-checkbox')['default']
    IvueCheckboxGroup: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-checkbox-group')['default']
    IvueChip: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-chip')['default']
    IvueCircular: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-circular')['default']
    IvueCollapse: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-collapse')['default']
    IvueCollapsePanel: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-collapse-panel')['default']
    IvueContent: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-content')['default']
    IvueCountDown: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-count-down')['default']
    IvueCountUp: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-count-up')['default']
    IvueDatePicker: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-date-picker')['default']
    IvueIcon: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-icon')['default']
    IvueInput: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-input')['default']
    IvueList: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-list')['default']
    IvueListItem: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-list-item')['default']
    IvueOption: typeof import('ivue-material-plus/dist/unplugin-vue-components/es')['IvueOption']
    IvueOptionGroup: typeof import('ivue-material-plus/dist/unplugin-vue-components/es')['IvueOptionGroup']
    IvuePage: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-page')['default']
    IvueProgress: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-progress')['default']
    IvueRadio: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-radio')['default']
    IvueRadioGroup: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-radio-group')['default']
    IvueSelect: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-select')['default']
    IvueSpin: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-spin')['default']
    IvueStep: typeof import('ivue-material-plus/dist/unplugin-vue-components/es')['IvueStep']
    IvueSteps: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-steps')['default']
    IvueSwitch: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-switch')['default']
    IvueTab: typeof import('ivue-material-plus/dist/unplugin-vue-components/es')['IvueTab']
    IvueTabItem: typeof import('ivue-material-plus/dist/unplugin-vue-components/es')['IvueTabItem']
    IvueTable: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-table')['default']
    IvueTableColumn: typeof import('ivue-material-plus/dist/unplugin-vue-components/es')['IvueTableColumn']
    IvueTabs: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-tabs')['default']
    IvueTooltip: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-tooltip')['default']
    IvueUpload: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-upload')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-loading')['IvueLoadingDirective']
    vTouch: typeof import('ivue-material-plus/dist/unplugin-vue-components/es/ivue-touch')['Touch']
  }
}
